### PR TITLE
Add flatlamp source to micado subpackage

### LINKED ISSUE #4: Create MICADO flat field source
There should be a flat field source / calibration lamp for MICADO.

This should create an almost homogeneous illumination. E.g. something like a low-order spherically-symmetric polynomial.

### PR DESCRIPTION
**Pull request by hugobuddel**
Add a flatlamp source to micado subpackage in order to simulate flat fields.

Also renames micado.empty_sky to micado.darkness, as that is actually what it should simulate.

Closes #4

### CODE REVIEW

**Comment by miguelverdugo** [comment]
Hi, 

Do we know the characteristic of the flatlamp of MICADO (e.g. temperature, luminance, etc)? What can be expected of illumination across the FoV? In most real cases, it isn't uniform and need to be fitted before applying it to real data. I could take care of it.

**Comment by hugobuddel** [comment]
> Do we know the characteristic of the flatlamp of MICADO (e.g. temperature, luminance, etc)? What can be expected of illumination across the FoV? In most real cases, it isn't uniform and need to be fitted before applying it to real data. I could take care of it.

I've shared a document from Gabriele Rodeghiero on the flat field illumination pattern. I'm not attaching it to the issue/PR because I'm not sure we can make it public.

It seems to be a spherically symmetric parabola with the peak in the center of the FoV and dropping to about 90% at the edges. Which is about what I expected.

I don't know what the absolute value of the illumination is, or the temperature of the lamp. There is some more information in this PDR document: 043_ELT-TRE-MCD-56301-0023_2.1_MICADO_Calibration_Assembly_Design_and_Analysis_Report.pdf
But those values are not that important.

**Comment by hugobuddel** [comment]
Oh, note that this particular implementation of the flat field source does not make sense because it is a point source.

Although maybe you could say that the flat field is a point source with a huge PSF!

**Comment by miguelverdugo** [comment]
Thanks for the information regarding flatfield patterns

Yes, these are the kind of patterns I've seen in real data. The tilt of the detectors also influences the continuity, but is another issue.  I see two ways forward.

1) Use these pre-calculated patterns as source for the flatfield. This would be very MICADO specific of course.

2) Use a simplified version, like suggested before, described by some polynomials of different degrees, depending what the user would like to use. This is more general. 

1) is more exact, 2) is more flexible and probably enough for any scientific and development  purposes. 

Regarding the temperature of the lamp. It isn't important for the imaging mode, but it is for the spectroscopic mode as the temperature determines the pattern along the spectral axis.

**Comment by hugobuddel** [comment]
For the moment I'd say: let's do what is the easiest to achieve.

At some point both your options are necessary:

1. Predefined values can be used to create the most realistic simulations. We could use actual measurements of the flat field and give these as an FITS file or so. This would be useful for the science team and for the data flow team (me) to test realistic cases.

2. A parametrization would allow more complex tests for the validation of the pipelines. E.g. it could be studied how well the algorithms can recover the flat field if some of the lamps break or something like that. (But having option 1 would make it possible for the user to create this input themselves.)

At the moment I do not have access to actual flat field data.

**Comment by hugobuddel** [comment]
FYI, about the continuity: one of the things that I'd like to do in the pipeline is decouple the gain variations between the detectors from the large scale illumination pattern of the lamps.

That is, if the illumination pattern of the lamp is relatively smooth, then it can be modeled over the detector edges. Any residual discrete variation of the fluxes measured on different detectors is then due to gain variations of the full detectors. (We have no specific reasons to assume these inter-detector gain variations to be different from zero though.)

Gain variations between individual pixels are indistinguishable from QE variations between pixels and will thus be captured by the flat field.

**Comment by hugobuddel** [comment]
Thanks for the example Kieran! Something like this would indeed be great. I'm currently first adding all the MICADO hardware in the IMDB to MicadoWISE, after that I can return to this. (Using empty_sky as flatlamp for now.) Miguel, feel free to commit to this branch if you feel like taking this on.

**Comment by hugobuddel** [comment]
I've updated the flatlamp and it now has a parabolic shape.

It uses a flat spectrum, and apparently it is not enough to just give it the end points. It needs about 200 points in between (all with the same value). The BlackBody didn't work either, but not sure why.

I'll do some more experiments. E.g. currently the amplitude is rather arbitrary, need to figure out what it should be.

**Review by astronomyk — APPROVED** [review]

**Pull request merged**
